### ISSUE TITLE
Client, integrate Biconomy SDK with social login to create a SCW

### ISSUE THREAD

**Issue by sebpalluel** [sebpalluel/web3-monorepo#103]
- https://biconomy.gitbook.io/sdk/guides/next.js/setting-up-social-login
- https://biconomy.gitbook.io/sdk/guides/next.js/setting-up-smart-account-with-sociallogin
- https://biconomy.gitbook.io/sdk/guides/register-dapp-on-dashboard-and-fund-gas-tank
- https://biconomy.gitbook.io/sdk/guides/next.js/code-examples/gasless-transactions-code-example
- https://biconomy.gitbook.io/sdk/guides/sdk-compatibility
- https://github.com/bcnmy/sdk-examples/tree/master/nextjs-biconomy-web3Auth
- https://forum.biconomy.io/
- https://github.com/orgs/Web3Auth/discussions

**Comment by sebpalluel** [comment]
Replace SIWE with SSX from spruce: https://docs.ssx.id/appendix/using-ssx-with-nextauth

**Comment by Wozacosta** [comment]
What do you think of their sdk so far?

**Comment by sebpalluel** [comment]
At the moment, I consider it to be one of the most advanced options available. However, the new dashboard is yet to be released, and it may take some time before it's ready for production. Additionally, it's unclear whether they will be using the new TSS version of Web3Auth or continuing with the Shamir Secret Sharing one.

If you want to use all the features, such as gasless and batched transactions, with the current dashboard, you will need to implement the old Mexa SDK and follow the documentation provided at https://docs.biconomy.io/.

Unipass is another option for Account Abstraction, but their implementation doesn't allow for the use of a web3 wallet. Moreover, they are currently developing their own authentication network and Account Abstraction features, which may be a challenging task for a single entity.

The good news is that Biconomy has forked the ERC-4337 smart contracts implementation from the Infinitism team, and it was recently announced that the contracts have been audited by OpenZeppelin: https://twitter.com/erc4337/status/1631087958949531648.
